Implement APIs for both platform configuration + guest launch ioctls.
enarx/snp pull request #7
Opened 2021-08-13 02:49 UTC by tfanelli-rh

Tested on Milan hardware.

2021-08-13 06:52 UTC, haraldh commented
Seems like this will require to bump the minimal rust version to 1.46 in https://github.com/enarx/snp/blob/main/.github/workflows/test.yml#L24

```
error[E0658]: `if` is not allowed in a `const fn`
Error:   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/vmm-sys-util-0.7.0/src/linux/epoll.rs:33:1
   |
33 | / bitflags! {
34 | |     /// The type of events we can monitor a file descriptor for.
35 | |     pub struct EventSet: u32 {
36 | |         /// The associated file descriptor is available for read operations.
...  |
68 | |     }
69 | | }
   | |_^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/49146
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

2021-08-13 07:00 UTC, haraldh commented
For the failing [check-spdx-headers](https://github.com/enarx/snp/pull/7/checks?check_run_id=3318559825#step:3:8) to pass, you just have to git rebase to current origin.

2021-08-13 08:10 UTC, haraldh requested changes

2021-08-13 08:10 UTC, haraldh commented on src/launch/mod.rs
> +    pub fn to_u16(&self) -> u16 {
Why not use `PolicyFlags::bits()` here?

2021-08-16 02:52 UTC, tfanelli-rh commented on src/launch/mod.rs
> +    pub fn to_u16(&self) -> u16 {
Fixed.

2021-08-16 03:32 UTC, tfanelli-rh commented
For some reason, I'm getting panics/errors on the `Doc-tests`.

```
   Doc-tests snp
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/thread/mod.rs:1269:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0 (53cb7b09b 2021-06-17) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no --crate-type lib

query stack during panic:
end of query stack
```

2021-08-16 13:41 UTC, tfanelli-rh commented
At the moment, this does not use the `sev-iocuddle` crate. I intend to change that with upcoming changes now that I see what details `snp` and `sev` share.

2021-08-16 13:59 UTC, tfanelli-rh commented on src/util/mod.rs
> +        Ok(t)
Fixed

2021-08-16 14:02 UTC, tfanelli-rh commented on src/launch/mod.rs
> +    pub fn to_u16(&self) -> u16 {
Fixed

2021-08-16 14:33 UTC, haraldh commented
> For the failing [check-spdx-headers](https://github.com/enarx/snp/pull/7/checks?check_run_id=3318559825#step:3:8) to pass, you just have to git rebase to current `origin/main`.

This still applies.. please rebase to `origin/main`:
```
$ git fetch origin
$ git rebase origin/main
```

2021-08-16 14:34 UTC, haraldh commented
> Seems like this will require to bump the minimal rust version to 1.46 in https://github.com/enarx/snp/blob/main/.github/workflows/test.yml#L24
> 
> ```
> error[E0658]: `if` is not allowed in a `const fn`
> Error:   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/vmm-sys-util-0.7.0/src/linux/epoll.rs:33:1
>    |
> 33 | / bitflags! {
> 34 | |     /// The type of events we can monitor a file descriptor for.
> 35 | |     pub struct EventSet: u32 {
> 36 | |         /// The associated file descriptor is available for read operations.
> ...  |
> 68 | |     }
> 69 | | }
>    | |_^
>    |
>    = note: for more information, see https://github.com/rust-lang/rust/issues/49146
>    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
> ```

```diff
diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
index 7540f52..9f255d6 100644
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -21,7 +21,7 @@ jobs:
           - nightly
           - beta
           - stable
-          - 1.42.0
+          - 1.46.0
         profile:
           - name: debug
           - name: release
```

2021-08-16 16:11 UTC, tfanelli-rh commented
> > For the failing [check-spdx-headers](https://github.com/enarx/snp/pull/7/checks?check_run_id=3318559825#step:3:8) to pass, you just have to git rebase to current `origin/main`.
> 
> This still applies.. please rebase to `origin/main`:
> 
> ```
> $ git fetch origin
> $ git rebase origin/main
> ```

I've rebased with `origin/main`, but the test still fails.

```
$ git branch
* guest_launch
  main
$ git fetch origin 
$ git rebase origin/main
Current branch guest_launch is up to date.
$ git push -f origin guest_launch 
Everything up-to-date

```

2021-08-16 16:12 UTC, connorkuehl requested changes
Nice job, @tfanelli-rh!

There are a couple of things that need to change for this PR.

The first, I suspect, is that you've been reading too closely to the SNP firmware spec. It's vital that we understand the firmware spec, but it isn't _technically_ the interface this code should be programming against. The actual interface you need to program against is the Linux kernel ioctls exported to userspace by Brijesh's hypervisor series.

The reason why I mention this at all is because your doc comments associated with each of the structs mention system physical addresses as well as taking only certain bits of them. Brijesh's ioctl documentation doesn't mention these at all, and as expected, they seem to only care about userspace virtual addresses. 

Please double check the doc comments you're exporting as well as the fields to make sure they align with the structs exported by the kernel. Please update your doc comments accordingly.

The second thing is that I think we should also pause on this PR, get `sev-iocuddle` package-worthy, release it to crates.io, and then finally consume it here in `snp`. Similarly, the `sev` crate will need to be updated to be downstream of `sev-iocuddle` so we can realize the benefits of factoring that code out into `sev-iocuddle` in the first place. Otherwise, we run the risk of maintaining the same code in multiple places, which is not fun.

2021-08-16 16:12 UTC, connorkuehl commented on src/launch/mod.rs
> +    pub id_auth_uaddr: u64,
Not sPAs.

2021-08-16 16:14 UTC, connorkuehl commented
> > > For the failing [check-spdx-headers](https://github.com/enarx/snp/pull/7/checks?check_run_id=3318559825#step:3:8) to pass, you just have to git rebase to current `origin/main`.
> > 
> > 
> > This still applies.. please rebase to `origin/main`:
> > ```
> > $ git fetch origin
> > $ git rebase origin/main
> > ```
> 
> I've rebased with `origin/main`, but the test still fails.
> 
> ```
> $ git branch
> * guest_launch
>   main
> $ git fetch origin 
> $ git rebase origin/main
> Current branch guest_launch is up to date.
> $ git push -f origin guest_launch 
> Everything up-to-date
> ```

What is your `origin` remote?

```
$ git remote get-url origin
```

If it's not this repo, you'll want to either:

```
$ git remote add upstream https://github.com/enarx/snp
$ git fetch upstream
$ git rebase upstream/master
```

or just a one-off (not recommended):

```
$ git fetch https://github.com/enarx/snp master
$ git rebase FETCH_HEAD
```

2021-08-20 14:53 UTC, tfanelli-rh commented
Regarding the `check-spdx-headers` test failing:
```
$ git fetch upstream
$ git rebase upstream/main
Current branch guest_launch is up to date.
```
I'll take a look into why this is.

2021-08-20 14:56 UTC, connorkuehl commented
Could it be a bug in the spdx action?

```
2021-08-20T14:50:33.9757504Z Traceback (most recent call last):
2021-08-20T14:50:33.9759198Z   File "/home/runner/work/_actions/enarx/spdx/master/verify-spdx-headers", line 120, in <module>
2021-08-20T14:50:33.9760158Z     print(f"{license:16} {path}")
2021-08-20T14:50:33.9761015Z TypeError: unsupported format string passed to NoneType.__format__
```

2021-08-20 17:36 UTC, tfanelli-rh commented
> Regarding the `check-spdx-headers` test failing:
> 
> ```
> $ git fetch upstream
> $ git rebase upstream/main
> Current branch guest_launch is up to date.
> ```
> 
> I'll take a look into why this is.

Fixed.

2021-08-23 12:49 UTC, haraldh commented
> > Seems like this will require to bump the minimal rust version to 1.46 in https://github.com/enarx/snp/blob/main/.github/workflows/test.yml#L24
> > ```
> > error[E0658]: `if` is not allowed in a `const fn`
> > Error:   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/vmm-sys-util-0.7.0/src/linux/epoll.rs:33:1
> >    |
> > 33 | / bitflags! {
> > 34 | |     /// The type of events we can monitor a file descriptor for.
> > 35 | |     pub struct EventSet: u32 {
> > 36 | |         /// The associated file descriptor is available for read operations.
> > ...  |
> > 68 | |     }
> > 69 | | }
> >    | |_^
> >    |
> >    = note: for more information, see https://github.com/rust-lang/rust/issues/49146
> >    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
> > ```
> 
> ```diff
> diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
> index 7540f52..9f255d6 100644
> --- a/.github/workflows/test.yml
> +++ b/.github/workflows/test.yml
> @@ -21,7 +21,7 @@ jobs:
>            - nightly
>            - beta
>            - stable
> -          - 1.42.0
> +          - 1.46.0
>          profile:
>            - name: debug
>            - name: release
> ```

Just add a commit bumping the version and you'll be fine

2021-08-24 08:46 UTC, haraldh approved these changes

2021-08-24 14:40 UTC, connorkuehl requested changes
Blocking until it can consume sev-iocuddle from crates.io.

2021-09-03 16:56 UTC, closed without merging